/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba.ventana;
import entidades.*;
import expediente_tramite.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tda.*;
/**
 *
 * @author nemi
 */
public class Departamentos extends javax.swing.JFrame {

    private ListaSimpleEnlazada<Expediente> expedientes = new ListaSimpleEnlazada<>();
    private ListaSimpleEnlazada<Dependencias> dependencias = new ListaSimpleEnlazada<>();
    private ListaSimpleEnlazada<Expediente> expfinalizados = new ListaSimpleEnlazada<>();
    private DefaultTableModel modelo;
    
    public Departamentos(ListaSimpleEnlazada<Expediente> expedientes, ListaSimpleEnlazada<Dependencias> dependencias, ListaSimpleEnlazada<Expediente> expfin) {
        initComponents();
        this.expedientes = expedientes;
        this.expfinalizados = expfin;
        this.dependencias = dependencias;
        if (!this.dependencias.esVacia()){
            for (int i = 1; i <= this.dependencias.longitud(); i++) {
                this.jComboBox1.addItem(this.dependencias.iesimo(i).getNombre());
                this.jComboBox2.addItem(this.dependencias.iesimo(i).getNombre());
                this.jComboBox3.addItem(this.dependencias.iesimo(i).getNombre());
            }
        }
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("PRIORIDAD");
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("EMAIL");
        modelo.addColumn("ASUNTO");
        modelo.addColumn("Fecha Registro");
        modelo.addColumn("TIPO");
        this.jTable1.setModel(modelo);
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
        jComboBox3.setSelectedIndex(-1);
        this.jTextField4.setEditable(false);
        this.jTextField5.setEditable(false);
        this.jTextField4.setText("Departamento de ---");
        this.jTextField5.setText("Jefe: ---");
    }
    
    public Departamentos(){
        setSize(1352, 769);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1352, 819));
        setMinimumSize(new java.awt.Dimension(1352, 819));
        setPreferredSize(new java.awt.Dimension(1352, 819));
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 140, 160, 40);

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 150, 72, 23);

        jButton2.setText("MOSTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 280, 85, 23);

        jButton3.setText("VOLVER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 730, 100, 23);

        jLabel9.setText("<-----");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 730, 33, 16);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(310, 270, 270, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 370, 628, 346);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(836, 43, 0, 0);

        jLabel6.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Añadir documento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 380, 180, 38);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(850, 450, 76, 22);

        jLabel7.setText("Título");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(760, 450, 80, 16);

        jLabel8.setText("Remitente");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 500, 90, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(850, 500, 76, 22);

        jButton7.setText("FINALIZAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(980, 260, 100, 23);

        jLabel11.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 51));
        jLabel11.setText("Finalizar trámite");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(770, 250, 162, 38);

        jButton8.setText("Ir a expedientes finalizados");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1110, 640, 200, 23);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(50, 330, 255, 22);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(390, 330, 287, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("mostrar por departamento");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 290, 250, 25);

        jLabel12.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 51));
        jLabel12.setText("Seleccione el departamento a enviar");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 100, 360, 38);

        jLabel3.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Seleccione departamento a mover");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(760, 100, 380, 38);

        jButton4.setText("MOVER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1100, 150, 72, 23);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(760, 140, 320, 40);

        jLabel13.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 51));
        jLabel13.setText("del expediente");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 100, 180, 30);

        jLabel14.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 51));
        jLabel14.setText("ACCIONES:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(250, 20, 470, 38);

        jLabel15.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("Introducir el ID");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 70, 170, 30);

        jLabel16.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 51));
        jLabel16.setText("Desea enivar expediente nuevo a un departamento?");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(250, 60, 470, 38);

        jComboBox3.setToolTipText("");
        jComboBox3.setName(""); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(250, 140, 280, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setText("Seleccione los expedientes a");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 260, 260, 25);

        jLabel5.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("Desea mover expediente existente a un departamento?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 60, 520, 38);

        jLabel18.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 51));
        jLabel18.setText("para el expediente?");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(780, 350, 240, 38);

        jLabel19.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 51));
        jLabel19.setText("Desea finalizar el trámite del expediente seleccionado?");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(750, 210, 540, 38);

        jLabel20.setFont(new java.awt.Font("NSimSun", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 51));
        jLabel20.setText("Desea añadir un documento de referencia");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(780, 320, 380, 38);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 60, 200, 130);

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 60, 500, 130);

        jPanel3.setBackground(new java.awt.Color(102, 255, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(740, 60, 560, 130);

        jPanel4.setBackground(new java.awt.Color(102, 255, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(740, 200, 560, 100);

        jPanel5.setBackground(new java.awt.Color(102, 255, 153));

        jButton6.setText("Añadir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton6)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(740, 320, 460, 270);

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        jButton5.setText("Ir a consultar información");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(1110, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(697, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1340, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Llenar_Dependencia();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Llenar_Dependencia()
    {
        this.jTable1.setModel(modelo);
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++)
        {
            modelo.removeRow(0);
        }
        Cola<Expediente> colaAux = new Cola<>();
        Cola<Expediente> colaAlta = new Cola<>();
        Cola<Expediente> colaMedia = new Cola<>();
        Cola<Expediente> colaBaja = new Cola<>();
        String[] datos = new String[9];
        String opcion = (String)this.jComboBox1.getSelectedItem();
        if (opcion!= null){
            for (int i = 1; i <= this.dependencias.longitud(); i++) {
            if (opcion.equals(dependencias.iesimo(i).getNombre())){
                this.jTextField4.setText("Departamento de " + dependencias.iesimo(i).getNombre());
                this.jTextField5.setText("Jefe: " + dependencias.iesimo(i).getJefe());
                
                while(!dependencias.iesimo(i).getExpedientes().esVacia()){
                    Expediente exp = dependencias.iesimo(i).getExpedientes().desencolar();
                    String prioridad = exp.getPrioridad();
                    
                    if (prioridad.equalsIgnoreCase("Alta")){
                        colaAlta.encolar(exp);
                    }else if (prioridad.equalsIgnoreCase("Media")){
                        colaMedia.encolar(exp);
                    }else if (prioridad.equalsIgnoreCase("Baja")){
                        colaBaja.encolar(exp);
                    }
                }
                
                while (!colaAlta.esVacia()){
                    dependencias.iesimo(i).getExpedientes().encolar(colaAlta.desencolar());
                }
                while (!colaMedia.esVacia()){
                    dependencias.iesimo(i).getExpedientes().encolar(colaMedia.desencolar());
                }
                while (!colaBaja.esVacia()){
                    dependencias.iesimo(i).getExpedientes().encolar(colaBaja.desencolar());
                }
                
                while(!dependencias.iesimo(i).getExpedientes().esVacia()){
                    Expediente exp = dependencias.iesimo(i).getExpedientes().desencolar();
                    datos[0] = String.valueOf(exp.getIdentificador());
                    datos[1] = exp.getPrioridad();
                    datos[2] = String.valueOf(exp.getDatosint().getDni());
                    datos[3] = exp.getDatosint().getNombres();
                    datos[4] = String.valueOf(exp.getDatosint().getTelefono());
                    datos[5] = exp.getDatosint().getEmail();
                    datos[6] = exp.getAsunto();
                    datos[7] = exp.getFecharegistro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    datos[8] = exp.getDatosint().getTipo();
                    modelo.addRow(datos);
                    colaAux.encolar(exp);
                }
                
                while (!colaAux.esVacia()){
                    dependencias.iesimo(i).getExpedientes().encolar(colaAux.desencolar());
                }
            }
        }
        }
        
        this.jTable1.setDefaultEditor(Object.class, null);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Registro_Expediente ventanaRegistro = new Registro_Expediente(this.expedientes, this.dependencias, this.expfinalizados);
        ventanaRegistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Seguimiento_Expediente ventanaInformacion = new Seguimiento_Expediente(this.expedientes, this.dependencias, this.expfinalizados);
        ventanaInformacion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String titulo = this.jTextField2.getText();
        String remitente = this.jTextField3.getText();
        String departamento = (String)this.jComboBox1.getSelectedItem();
        int idbuscado = Integer.parseInt(this.jTextField1.getText());
        for (int i = 1; i <= dependencias.longitud(); i++) {
            if (dependencias.iesimo(i).getNombre().equalsIgnoreCase(departamento)){
                Cola<Expediente> aux = new Cola<>();
                while(!dependencias.iesimo(i).getExpedientes().esVacia()){
                    Expediente expaux = dependencias.iesimo(i).getExpedientes().desencolar();
                    if (expaux.getIdentificador() == idbuscado){
                        Documentos doc = new Documentos(departamento, titulo, remitente);
                        expaux.getDocumentos().agregar(doc);
                    }
                    aux.encolar(expaux);
                }
                
                while (!aux.esVacia()){
                    dependencias.iesimo(i).getExpedientes().encolar(aux.desencolar());
                }
            }
        }
        this.jTextField2.setText("");
        this.jTextField3.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String departamento = (String)this.jComboBox1.getSelectedItem();
        int idbuscado = Integer.parseInt(this.jTextField1.getText());
        for (int i = 1; i <= dependencias.longitud(); i++) {
            if (dependencias.iesimo(i).getNombre().equalsIgnoreCase(departamento)){
                Cola<Expediente> aux = new Cola<>();
                while(!dependencias.iesimo(i).getExpedientes().esVacia()){
                    Expediente expaux = dependencias.iesimo(i).getExpedientes().desencolar();
                    if (expaux.getIdentificador() == idbuscado){
                        LocalDateTime fecha = LocalDateTime.now();
                        if (expaux.getMovimientos() != null){
                            expaux.getMovimientos().iesimo(expaux.getMovimientos().longitud()).setFechafinal(fecha);
                        }
                        expaux.setFechafinalizacion(fecha);
                        this.expfinalizados.agregar(expaux);
                    }else{
                        aux.encolar(expaux);
                    }
                }
                
                while (!aux.esVacia()){
                    dependencias.iesimo(i).getExpedientes().encolar(aux.desencolar());
                }
            }
        }
        
        Llenar_Dependencia();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Expedientes_Finalizados frmExpedientesfinal = new Expedientes_Finalizados(this.expedientes, this.dependencias, expfinalizados);
        frmExpedientesfinal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        boolean mismo = false;
        int idbuscado = Integer.parseInt(this.jTextField1.getText());
        String inicio = (String)this.jComboBox1.getSelectedItem();
        String destino = (String)this.jComboBox2.getSelectedItem();
        if (inicio != destino){
            for (int i = 1; i <= dependencias.longitud(); i++) {
                if (dependencias.iesimo(i).getNombre().equalsIgnoreCase(inicio)){
                    Cola<Expediente> aux = new Cola<>();
                    while(!dependencias.iesimo(i).getExpedientes().esVacia()){
                        Expediente expaux = dependencias.iesimo(i).getExpedientes().desencolar();
                        if (expaux.getIdentificador() == idbuscado){
                            for (int j = 1; j <= dependencias.longitud(); j++) {
                                if (dependencias.iesimo(j).getNombre().equalsIgnoreCase(destino)){
                                    LocalDateTime fecha = LocalDateTime.now();
                                    Movimientos mov = new Movimientos(destino, fecha, null);
                                    expaux.getMovimientos().iesimo(expaux.getMovimientos().longitud()).setFechafinal(fecha);
                                    expaux.getMovimientos().agregar(mov);
                                    dependencias.iesimo(j).getExpedientes().encolar(expaux);
                                    encontrado = true;

                                }
                            }
                        }else{
                            aux.encolar(expaux);
                        }
                    }

                    while (!aux.esVacia()){
                        dependencias.iesimo(i).getExpedientes().encolar(aux.desencolar());
                    }
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR: lo esta moviendo al mismo departamento");
            mismo = true;
        }
        if (!encontrado && !mismo){
            JOptionPane.showMessageDialog(null, "ERROR: no se encontro el id: " + idbuscado + "\nEn la cola: " + inicio);
        }

        Llenar_Dependencia();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int idbuscado = Integer.parseInt(this.jTextField1.getText());
        String opcion = (String)this.jComboBox3.getSelectedItem();
        if (!expedientes.esVacia()){
            for (int i = 1; i <= expedientes.longitud(); i++) {
            if (expedientes.iesimo(i).getIdentificador() == idbuscado){
                for (int j = 1; j <= this.dependencias.longitud(); j++) {
                    if (opcion.equals(dependencias.iesimo(j).getNombre())){
                        LocalDateTime fecha = LocalDateTime.now();
                        Movimientos mov = new Movimientos(opcion, fecha, null);
                        if (expedientes.iesimo(i).getMovimientos().esVacia()){
                            expedientes.iesimo(i).getMovimientos().agregar(mov);
                            dependencias.iesimo(j).getExpedientes().encolar(expedientes.iesimo(i));

                        }
                        
                    }
                    
                }
            }
        }
        }
        
        Llenar_Dependencia();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Departamentos().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
