/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba.ventana;
import expediente_tramite.*;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tda.*;
/**
 *
 * @author nemi
 */
public class Expedientes_Finalizados extends javax.swing.JFrame {

    /**
     * Creates new form Expedientes_Finalizados
     */
    private ListaSimpleEnlazada<Expediente> expedientes = new ListaSimpleEnlazada<>();
    private ListaSimpleEnlazada<Dependencias> dependencias = new ListaSimpleEnlazada<>();
    private ListaSimpleEnlazada<Expediente> expfinalizados = new ListaSimpleEnlazada<>();
    private DefaultTableModel modelo;
    
    public Expedientes_Finalizados() {
        initComponents();
        setSize(1071, 399);
    }
    
    public Expedientes_Finalizados(ListaSimpleEnlazada<Expediente> expedientes, ListaSimpleEnlazada<Dependencias> dependencias, ListaSimpleEnlazada<Expediente> expfin) {
        initComponents();
        this.expedientes = expedientes;
        this.expfinalizados = expfin;
        this.dependencias = dependencias;
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("PRIORIDAD");
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("EMAIL");
        modelo.addColumn("ASUNTO");
        modelo.addColumn("Fecha Registro");
        modelo.addColumn("Fecha Finalizacion");
        modelo.addColumn("TIPO");
        this.jTable1.setModel(modelo);
        jComboBox1.setSelectedIndex(-1);
        Llenar_Expedientes_Finalizados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1071, 450));
        setMinimumSize(new java.awt.Dimension(1071, 450));
        setPreferredSize(new java.awt.Dimension(1071, 450));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(34, 85, 730, 238);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("EXPEDIENTES FINALIZADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(284, 35, 293, 32);

        jLabel2.setText("FILTRAR POR ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(785, 38, 84, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(904, 35, 105, 22);

        jButton1.setText("Volver...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(29, 355, 81, 23);

        jButton2.setText("Filtrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(904, 93, 105, 23);

        jLabel3.setText("FILTRAR POR PRIORIDAD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(834, 181, 133, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Media", "Baja" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(865, 215, 72, 22);

        jButton3.setText("Filtrar por prioridad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(834, 337, 132, 23);

        jButton4.setText("Mostrar Todo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(29, 35, 102, 23);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Departamentos frmDependencias = new Departamentos(this.expedientes, this.dependencias, expfinalizados);
        frmDependencias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean encontrado = false;
        int idbuscado = Integer.parseInt(this.jTextField1.getText());
        this.jTable1.setModel(modelo);
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++)
        {
            modelo.removeRow(0);
        }
        
        
        
        if (!this.expfinalizados.esVacia()){
            for (int i = 1; i <= expfinalizados.longitud(); i++) {
                if (expfinalizados.iesimo(i).getIdentificador() == idbuscado){
                    String[] datos = new String[10];
                    datos[0] = String.valueOf(expfinalizados.iesimo(i).getIdentificador());
                    datos[1] = expfinalizados.iesimo(i).getPrioridad();
                    datos[2] = String.valueOf(expfinalizados.iesimo(i).getDatosint().getDni());
                    datos[3] = expfinalizados.iesimo(i).getDatosint().getNombres();
                    datos[4] = String.valueOf(expfinalizados.iesimo(i).getDatosint().getTelefono());
                    datos[5] = expfinalizados.iesimo(i).getDatosint().getEmail();
                    datos[6] = expfinalizados.iesimo(i).getAsunto();
                    datos[7] = expfinalizados.iesimo(i).getFecharegistro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    datos[8] = expfinalizados.iesimo(i).getFechafinalizacion().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    datos[9] = expfinalizados.iesimo(i).getDatosint().getTipo();
                    modelo.addRow(datos);
                    encontrado = true;
                }
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null, "No se encontro el ID: " + idbuscado);
        }
        this.jTable1.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String prioridad = (String)this.jComboBox1.getSelectedItem();
        this.jTable1.setModel(modelo);
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++)
        {
            modelo.removeRow(0);
        }
        
        
        
        if (!this.expfinalizados.esVacia()){
            for (int i = 1; i <= expfinalizados.longitud(); i++) {
                if (expfinalizados.iesimo(i).getPrioridad().equals(prioridad)){
                    String[] datos = new String[10];
                    datos[0] = String.valueOf(expfinalizados.iesimo(i).getIdentificador());
                    datos[1] = expfinalizados.iesimo(i).getPrioridad();
                    datos[2] = String.valueOf(expfinalizados.iesimo(i).getDatosint().getDni());
                    datos[3] = expfinalizados.iesimo(i).getDatosint().getNombres();
                    datos[4] = String.valueOf(expfinalizados.iesimo(i).getDatosint().getTelefono());
                    datos[5] = expfinalizados.iesimo(i).getDatosint().getEmail();
                    datos[6] = expfinalizados.iesimo(i).getAsunto();
                    datos[7] = expfinalizados.iesimo(i).getFecharegistro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    datos[8] = expfinalizados.iesimo(i).getFechafinalizacion().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    datos[9] = expfinalizados.iesimo(i).getDatosint().getTipo();
                    modelo.addRow(datos);
                }
            }
        }
        this.jTable1.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Llenar_Expedientes_Finalizados();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void Llenar_Expedientes_Finalizados(){
        this.jTable1.setModel(modelo);
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++)
        {
            modelo.removeRow(0);
        }
        
        
        
        if (!this.expfinalizados.esVacia()){
            for (int i = 1; i <= expfinalizados.longitud(); i++) {
                String[] datos = new String[10];
                datos[0] = String.valueOf(expfinalizados.iesimo(i).getIdentificador());
                datos[1] = expfinalizados.iesimo(i).getPrioridad();
                datos[2] = String.valueOf(expfinalizados.iesimo(i).getDatosint().getDni());
                datos[3] = expfinalizados.iesimo(i).getDatosint().getNombres();
                datos[4] = String.valueOf(expfinalizados.iesimo(i).getDatosint().getTelefono());
                datos[5] = expfinalizados.iesimo(i).getDatosint().getEmail();
                datos[6] = expfinalizados.iesimo(i).getAsunto();
                datos[7] = expfinalizados.iesimo(i).getFecharegistro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                if (expfinalizados.iesimo(i).getFechafinalizacion() != null){
                    datos[8] = expfinalizados.iesimo(i).getFechafinalizacion().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                }else{
                    datos[8] = "";
                }
                datos[9] = expfinalizados.iesimo(i).getDatosint().getTipo();
                modelo.addRow(datos);
            }
        }
        this.jTable1.setDefaultEditor(Object.class, null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expedientes_Finalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expedientes_Finalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expedientes_Finalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expedientes_Finalizados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expedientes_Finalizados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
