/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba.ventana;

import expediente_tramite.*;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import tda.*;

/**
 *
 * @author nemi
 */
public class Seguimiento_Expediente extends javax.swing.JFrame {

    /**
     * Creates new form Informacion
     */
    private ListaSimpleEnlazada<Expediente> expedientes = new ListaSimpleEnlazada<>();
    private ListaSimpleEnlazada<Dependencias> dependencias = new ListaSimpleEnlazada<>();
    private ListaSimpleEnlazada<Expediente> expfinalizados = new ListaSimpleEnlazada<>();
    private DefaultTableModel modelo;
    private DefaultTableModel modelo2;
    
    public Seguimiento_Expediente() {
        initComponents();
        setSize(1297, 678);
    }

    public Seguimiento_Expediente(ListaSimpleEnlazada<Expediente> expedientes, ListaSimpleEnlazada<Dependencias> dependencias, ListaSimpleEnlazada<Expediente> expfinalizados) {
        initComponents();
        this.expedientes = expedientes;
        this.expfinalizados = expfinalizados;
        this.dependencias = dependencias;
        modelo2 = new DefaultTableModel();
        modelo = new DefaultTableModel();
        modelo.addColumn("MOVIMIENTO");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");
        modelo2.addColumn("Departamento");
        modelo2.addColumn("Titulo");
        modelo2.addColumn("Remitente");
        this.jTable1.setModel(modelo);
        this.jTable2.setModel(modelo2);
    }
    
    public void Seguimiento()
    {
        int id = Integer.parseInt(this.jTextField1.getText());
        this.jTable1.setModel(modelo);
        int filas = this.jTable1.getRowCount();
        for (int i = 0; i < filas; i++)
        {
            modelo.removeRow(0);
        }
        
        this.jTable2.setModel(modelo2);
        int filas2 = this.jTable2.getRowCount();
        for (int i = 0; i < filas2; i++) {
            modelo2.removeRow(0);
        }
        
        String[] datos2 = new String[3];
        
        String[] datos = new String[3];
        
        for (int i = 1; i <= expedientes.longitud(); i++) {
            if (id == expedientes.iesimo(i).getIdentificador()){
                datos[0] = "Expediente";
                datos[1] = expedientes.iesimo(i).getFecharegistro().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                if (expedientes.iesimo(i).getFechafinalizacion() == null){
                    datos[2] = "---";
                }else{
                    datos[2] = expedientes.iesimo(i).getFechafinalizacion().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                }
                modelo.addRow(datos);
                
                for (int j = 1; j <= expedientes.iesimo(i).getMovimientos().longitud(); j++) {
                    datos[0] = expedientes.iesimo(i).getMovimientos().iesimo(j).getMovimiento();
                    datos[1] = expedientes.iesimo(i).getMovimientos().iesimo(j).getFechainicio().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    if (expedientes.iesimo(i).getMovimientos().iesimo(j).getFechafinal() == null){
                        datos[2] = "---";
                    }else{
                        datos[2] = expedientes.iesimo(i).getMovimientos().iesimo(j).getFechafinal().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
                    }
                    modelo.addRow(datos);
                }
                
                for (int j = 1; j <= expedientes.iesimo(i).getDocumentos().longitud(); j++) {
                    datos2[0] = expedientes.iesimo(i).getDocumentos().iesimo(j).getDepartamento();
                    datos2[1] = expedientes.iesimo(i).getDocumentos().iesimo(j).getTitulo();
                    datos2[2] = expedientes.iesimo(i).getDocumentos().iesimo(j).getRemitente();
                    modelo2.addRow(datos2);
                }
            }
        }
        this.jTable1.setDefaultEditor(Object.class, null);
        this.jTable2.setDefaultEditor(Object.class, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1284, 714));
        setMinimumSize(new java.awt.Dimension(1284, 714));
        setPreferredSize(new java.awt.Dimension(1284, 714));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(34, 167, 537, 354);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(517, 64, 149, 22);

        jButton1.setText("Consultar información");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(517, 115, 149, 23);

        jButton2.setText("Volver...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(34, 623, 72, 23);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(635, 167, 607, 354);

        jLabel2.setText("MOVIMIENTOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(241, 139, 81, 16);

        jLabel3.setText("DOCUMENTOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(900, 139, 81, 16);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("INGRESAR ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Departamentos frmDependencias = new Departamentos(this.expedientes, this.dependencias, expfinalizados);
        frmDependencias.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Seguimiento();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguimiento_Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguimiento_Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguimiento_Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguimiento_Expediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguimiento_Expediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
